a=input("ENTER FIRST NUMBER:")
print(a)
b=input("ENTER SECOND NUMBER:")
print(b)
result=int(a)+int(b)
print(result)
result=int(a)-int(b)
print(result)
result=int(a)*int(b)
print(result)
result=int(a)/int(b)
print(result)
result=int(a)%int(b)
print(result)